//
// Created by Johan Pedersen on 23/03/2022.
//

#ifndef VISIBILITY_2_EXAMPLES_CONVEXITY_MEASURE_2_H
#define VISIBILITY_2_EXAMPLES_CONVEXITY_MEASURE_2_H

#endif //VISIBILITY_2_EXAMPLES_CONVEXITY_MEASURE_2_H
